name: CI
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
<<<<<<< Updated upstream:.github/workflows/gradle.yml
        run: ./gradlew  build --scan --no-daemon
=======
        run: ./gradlew  build --scan --no-daemon
>>>>>>> Stashed changes:.github/workflows/gradle.yaml
